# Generated by Django 5.2.4 on 2025-07-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Lecturer', 'Lecturer'), ('Invigilator', 'Invigilator'), ('Student', 'Student')], max_length=20),
        ),
    ]
