# Generated by Django 5.2.4 on 2025-07-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsapp', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
