# Generated by Django 5.2.4 on 2025-07-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsapp', '0005_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.CharField(unique=True, verbose_name=10),
        ),
    ]
